# Butterfly Theme Default Configuration

menu:
  首页: / || fa fa-home
  音乐: /music/ || fa fa-music
  电影: /movies/ || fa fa-film
  动漫: /anime/ || fa fa-tv
  漫画: /manga/ || fa fa-book
  小说: /novel/ || fa fa-book-open
  ASMR: /asmr/ || fa fa-headphones
  关于: /about/ || fa fa-user
  友情链接: /link/ || fa fa-link
  归档: /archives/ || fa fa-archive
  标签: /tags/ || fa fa-tags
  分类: /categories/ || fa fa-th

favicon: /img/favicon.png
avatar:
  img: /img/butterfly-icon.png
  effect: false

highlight:
  enable: false

prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

search:
  path: search.json
  field: post
  content: true
  format: striptags

footer:
  owner:
    enable: true
    copyright: true
  custom_text:
  runtime: true

social:
  fab fa-github: https://github.com/MIXUULSS || Github
  fas fa-envelope: /about/ || Email

font:
  font-size: 16px
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato, Roboto, "PingFang SC", "Microsoft YaHei", sans-serif