# Hexo Theme Butterfly
# https://github.com/jerryc127/hexo-theme-butterfly

# Theme
theme:
  # User interface
  uiux:
    # Global font settings
    # Don't modify the following unless you know how they work
    text_font_family:
    text_font_weight: 400
    site_name_font:
    site_name_font_weight: 400
    # Code
    code_font_family: 'JetBrains Mono'

# Menu
menu:
  首页: / || fa fa-home
  音乐: /music/ || fa fa-music
  电影: /movies/ || fa fa-film
  动漫: /anime/ || fa fa-tv
  漫画: /manga/ || fa fa-book
  小说: /novel/ || fa fa-book-open
  ASMR: /asmr/ || fa fa-headphones
  关于: /about/ || fa fa-user
  友情链接: /link/ || fa fa-link
  归档: /archives/ || fa fa-archive
  标签: /tags/ || fa fa-tags
  分类: /categories/ || fa fa-th

# Footer
footer:
  owner:
    enable: true
    since: 2025
  custom_text:
  copyright: true # Copyright of theme and framework

# Avatar
avatar:
  img: /img/avatar.png
  effect: true

# Cover
cover:
  # display the cover or not
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page
  position: front
  # when cover disabled, the cover picture will be shown
  default_cover:
    - /img/default_cover_0.jpg
    - /img/default_cover_1.jpg
    - /img/default_cover_2.jpg

# Article
article:
  # Post toc
  toc:
    enable: true
    number: false
    expand: false
    post_max_height: 420px
  # Post copyright
  copyright:
    enable: true
    default: 'CC BY-NC-SA 4.0'
    content: ''
    style: 'light'
  # Post meta
  meta_date:
    date: true
    updated: true

# Category & Tag
category_bar:
  enable: true
  limit: 12

# Highlight
highlight_theme: light

# Click effects
# The original issue: https://github.com/jerryc127/hexo-theme-butterfly/issues/608
click_effect:
  heart: true
  fireworks: false

# Word Count
wordcount:
  enable: true
  post_wordcount: true
  min2read: true

# Local Search
local_search:
  enable: true
  preload: false

# Font Awesome
fontawesome:
  # WebFont
  webfont: true
  # CDN Link of the Fontawesome JS
  # fontawesome_v6: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6/js/all.min.js
  # fontawesome_v5: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/js/all.min.js
  # fontawesome_v4: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@4.7.0/js/all.min.js

# Social
social:
  fa fa-github: https://github.com/MIXUULSS || Github
  fa fa-envelope: mailto:your-email@example.com || Email

# PWA
pwa:
  enable: false
  manifest: /manifest.json

# Visitors
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true